service: serverless-node

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: serverless-node-ks
    events:
      - s3:
          bucket: serverless-node-ks
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
      - s3:
          bucket: serverless-node-ks
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg